const mockUserData = {
    page: 1,
    pageSize: 10,
    total: 30,
    data: [
        {
            id: "1",
            name: "John",
            surname: "Doe",
            email: "john.doe@example.com",
            phone: "+1 555-123-4567",
            country: "USA",
            role: "Admin",
        },
        {
            id: "2",
            name: "Jane",
            surname: "Smith",
            email: "jane.smith@example.com",
            phone: "+44 20 7946 0958",
            country: "UK",
            role: "User",
        },
        {
            id: "3",
            name: "Alice",
            surname: "Johnson",
            email: "alice.johnson@example.com",
            phone: "+33 1 23 45 67 89",
            country: "France",
            role: "Manager",
        },
        {
            id: "4",
            name: "Robert",
            surname: "Brown",
            email: "robert.brown@example.com",
            phone: "+49 30 123456",
            country: "Germany",
            role: "User",
        },
        {
            id: "5",
            name: "Michael",
            surname: "Wilson",
            email: "michael.wilson@example.com",
            phone: "+61 2 1234 5678",
            country: "Australia",
            role: "Admin",
        },
        {
            id: "6",
            name: "Emma",
            surname: "Davis",
            email: "emma.davis@example.com",
            phone: "+81 3-1234-5678",
            country: "Japan",
            role: "User",
        },
        {
            id: "7",
            name: "William",
            surname: "Miller",
            email: "william.miller@example.com",
            phone: "+86 10 1234 5678",
            country: "China",
            role: "Manager",
        },
        {
            id: "8",
            name: "Olivia",
            surname: "Taylor",
            email: "olivia.taylor@example.com",
            phone: "+91 22 1234 5678",
            country: "India",
            role: "User",
        },
        {
            id: "9",
            name: "James",
            surname: "Anderson",
            email: "james.anderson@example.com",
            phone: "+55 11 1234-5678",
            country: "Brazil",
            role: "Admin",
        },
        {
            id: "10",
            name: "Sophia",
            surname: "Thomas",
            email: "sophia.thomas@example.com",
            phone: "+7 495 123-45-67",
            country: "Russia",
            role: "User",
        },
        {
            id: "11",
            name: "Liam",
            surname: "Moore",
            email: "liam.moore@example.com",
            phone: "+34 91 123 45 67",
            country: "Spain",
            role: "User",
        },
        {
            id: "12",
            name: "Isabella",
            surname: "Martin",
            email: "isabella.martin@example.com",
            phone: "+39 06 1234 5678",
            country: "Italy",
            role: "Manager",
        },
        {
            id: "13",
            name: "Mason",
            surname: "Lee",
            email: "mason.lee@example.com",
            phone: "+82 2 1234 5678",
            country: "South Korea",
            role: "Admin",
        },
        {
            id: "14",
            name: "Evelyn",
            surname: "Harris",
            email: "evelyn.harris@example.com",
            phone: "+27 11 123 4567",
            country: "South Africa",
            role: "User",
        },
        {
            id: "15",
            name: "Lucas",
            surname: "Clark",
            email: "lucas.clark@example.com",
            phone: "+48 22 123 45 67",
            country: "Poland",
            role: "Manager",
        },
        {
            id: "16",
            name: "Charlotte",
            surname: "Lewis",
            email: "charlotte.lewis@example.com",
            phone: "+31 20 123 4567",
            country: "Netherlands",
            role: "User",
        },
        {
            id: "17",
            name: "Benjamin",
            surname: "Walker",
            email: "benjamin.walker@example.com",
            phone: "+45 12 34 56 78",
            country: "Denmark",
            role: "Admin",
        },
        {
            id: "18",
            name: "Ava",
            surname: "Hall",
            email: "ava.hall@example.com",
            phone: "+46 8 123 4567",
            country: "Sweden",
            role: "User",
        },
        {
            id: "19",
            name: "Elijah",
            surname: "Allen",
            email: "elijah.allen@example.com",
            phone: "+41 31 123 45 67",
            country: "Switzerland",
            role: "User",
        },
        {
            id: "20",
            name: "Mia",
            surname: "Young",
            email: "mia.young@example.com",
            phone: "+1 555-987-6543",
            country: "Canada",
            role: "Manager",
        },
        {
            id: "21",
            name: "Noah",
            surname: "King",
            email: "noah.king@example.com",
            phone: "+52 55 1234 5678",
            country: "Mexico",
            role: "User",
        },
        {
            id: "22",
            name: "Harper",
            surname: "Wright",
            email: "harper.wright@example.com",
            phone: "+54 11 1234 5678",
            country: "Argentina",
            role: "User",
        },
        {
            id: "23",
            name: "Logan",
            surname: "Lopez",
            email: "logan.lopez@example.com",
            phone: "+66 2 123 4567",
            country: "Thailand",
            role: "Manager",
        },
        {
            id: "24",
            name: "Amelia",
            surname: "Scott",
            email: "amelia.scott@example.com",
            phone: "+63 2 123 4567",
            country: "Philippines",
            role: "Admin",
        },
        {
            id: "25",
            name: "Ethan",
            surname: "Green",
            email: "ethan.green@example.com",
            phone: "+34 91 234 56 78",
            country: "Spain",
            role: "User",
        },
        {
            id: "26",
            name: "Abigail",
            surname: "Baker",
            email: "abigail.baker@example.com",
            phone: "+47 22 123 45 67",
            country: "Norway",
            role: "User",
        },
        {
            id: "27",
            name: "Jacob",
            surname: "Gonzalez",
            email: "jacob.gonzalez@example.com",
            phone: "+60 3 123 4567",
            country: "Malaysia",
            role: "Manager",
        },
        {
            id: "28",
            name: "Aiden",
            surname: "Martinez",
            email: "aiden.martinez@example.com",
            phone: "+65 12 3456 7890",
            country: "Singapore",
            role: "User",
        },
        {
            id: "29",
            name: "Grace",
            surname: "Perez",
            email: "grace.perez@example.com",
            phone: "+62 21 123 4567",
            country: "Indonesia",
            role: "Admin",
        },
        {
            id: "30",
            name: "Jackson",
            surname: "Sanchez",
            email: "jackson.sanchez@example.com",
            phone: "+94 11 123 4567",
            country: "Sri Lanka",
            role: "User",
        },
    ],
};

export default mockUserData;
